name: chatapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^0.5.3+4
  provider: ^3.1.0
  http: ^0.12.0+2
  webview_flutter: ^0.3.13
  image_picker: ^0.6.1+4
  cached_network_image: ^1.1.1
  intl: ^0.15.8
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.1
  firebase_auth: ^0.14.0+4
  google_sign_in: ^4.0.6
  cloud_firestore: ^0.12.9+1
  firebase_storage: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/locale/
    # Locale
    - assets/locale/en/main.json
    - assets/locale/vi/main.json
    - assets/locale/en/common.json
    - assets/locale/vi/common.json

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
